const NODE_API_BASE = import.meta.env.VITE_NODE_API_BASE_URL
    || (import.meta.env.DEV
        ? 'http://localhost:3002/api/v1'
        : '/api/v1');

export const API_FEATURES = Object.freeze({
    adminAccounts: true,
    adminDictionaries: true,
    profile: true,
    schedule: true,
    lessonCreation: true,
    lessonChanges: true,
    classroom: true,
    diary: true,
    journal: true,
    homework: true,
    materials: true,
    messages: true,
    notifications: true,
    parentChildren: true,
    reviews: true,
});

export const API = {
    login: `${NODE_API_BASE}/auth/login`,
    register: `${NODE_API_BASE}/auth/register`,
    verifyEmail: `${NODE_API_BASE}/auth/verify-email`,
    resendVerification: `${NODE_API_BASE}/auth/resend-verification`,
    adminLogin: `${NODE_API_BASE}/admin/auth/login`,
    adminMe: `${NODE_API_BASE}/admin/auth/me`,
    adminLogout: `${NODE_API_BASE}/admin/auth/logout`,
    adminAccounts: `${NODE_API_BASE}/admin/accounts`,
    adminDashboardStats: `${NODE_API_BASE}/admin/dashboard/stats`,
    adminDictionaries: `${NODE_API_BASE}/admin/dictionaries`,
    adminDocuments: `${NODE_API_BASE}/admin/documents`,
    adminMaterials: `${NODE_API_BASE}/admin/materials`,
    adminParentChildren: `${NODE_API_BASE}/admin/parent-children`,
    adminReviews: `${NODE_API_BASE}/admin/reviews`,
    adminAccessibilityOffers: `${NODE_API_BASE}/admin/accessibility-offers`,
    adminStudents: `${NODE_API_BASE}/admin/students`,
    adminTariffs: `${NODE_API_BASE}/admin/tariffs`,
    adminTeachers: `${NODE_API_BASE}/admin/teachers`,
    forgotPassword: `${NODE_API_BASE}/auth/forgot-password`,
    resetPassword: `${NODE_API_BASE}/auth/reset-password`,

    me: `${NODE_API_BASE}/profile/me`,
    updateAccount: `${NODE_API_BASE}/profile/account`,
    parentChildren: `${NODE_API_BASE}/parent/children`,
    parentDashboard: `${NODE_API_BASE}/parent/dashboard`,
    teacherDashboardStats: `${NODE_API_BASE}/teacher/dashboard/stats`,
    teacherDashboardRating: `${NODE_API_BASE}/teacher/dashboard/rating`,
    accessibilityOffers: `${NODE_API_BASE}/accessibility-program/offers`,
    accessibilityApplications: `${NODE_API_BASE}/accessibility-program/applications`,
    studentParentLinkRequests: `${NODE_API_BASE}/student/parent-link-requests`,
    updateTeacherVisibility: `${NODE_API_BASE}/profile/teacher/visibility`,
    accountSecurity: `${NODE_API_BASE}/auth/security`,
    teacherOptions: `${NODE_API_BASE}/profile/teacher-options`,
    updateTeacher: `${NODE_API_BASE}/profile/teacher`,
    uploadTeacherPhoto: `${NODE_API_BASE}/profile/teacher/media/photo`,
    uploadTeacherVideo: `${NODE_API_BASE}/profile/teacher/media/video`,
    deleteTeacherMedia: `${NODE_API_BASE}/profile/teacher/media/delete`,
    teacherProfileMediaFiles: `${NODE_API_BASE}/profile/teacher/media`,
    uploadTeacherDocument: `${NODE_API_BASE}/profile/teacher/documents`,
    deleteTeacherDocument: `${NODE_API_BASE}/profile/teacher/documents/delete`,
    teacherDocumentFiles: `${NODE_API_BASE}/profile/teacher/documents`,
    updateStudent: `${NODE_API_BASE}/profile/student`,
    studentProfile: `${NODE_API_BASE}/profile/student`,
    schedule: `${NODE_API_BASE}/lessons/schedule`,
    requestLessonChange: `${NODE_API_BASE}/lessons/change-requests`,
    respondLessonChange: `${NODE_API_BASE}/lessons/change-requests/respond`,
    withdrawLessonChange: `${NODE_API_BASE}/lessons/change-requests/withdraw`,
    homework: `${NODE_API_BASE}/homework`,
    homeworkShow: `${NODE_API_BASE}/homework/show`,
    homeworkOptions: `${NODE_API_BASE}/homework/options`,
    createHomework: `${NODE_API_BASE}/homework`,
    submitHomework: `${NODE_API_BASE}/homework/submit`,
    reviewHomework: `${NODE_API_BASE}/homework/review`,
    cancelHomework: `${NODE_API_BASE}/homework/cancel`,
    markHomeworkViewed: `${NODE_API_BASE}/homework/viewed`,
    downloadHomeworkFile: `${NODE_API_BASE}/homework/download`,
    materials: `${NODE_API_BASE}/materials`,
    materialOptions: `${NODE_API_BASE}/materials/options`,
    materialShow: `${NODE_API_BASE}/materials/show`,
    materialDownload: `${NODE_API_BASE}/materials/download`,
    studentNotificationSettings: `${NODE_API_BASE}/notifications/student-settings`,
    studentDiary: `${NODE_API_BASE}/student/diary`,
    parentDiary: `${NODE_API_BASE}/parent/children/diary`,
    teacherJournal: `${NODE_API_BASE}/journal`,
    saveJournalResult: `${NODE_API_BASE}/journal/result`,
    classroomShow: `${NODE_API_BASE}/classroom/show`,
    classroomEvents: `${NODE_API_BASE}/classroom/events`,
    classroomSync: `${NODE_API_BASE}/classroom/sync`,
    classroomStart: `${NODE_API_BASE}/classroom/start`,
    classroomFinish: `${NODE_API_BASE}/classroom/finish`,
    classroomSendMessage: `${NODE_API_BASE}/classroom/send-message`,
    classroomMediaSignal: `${NODE_API_BASE}/classroom/media-signal`,
    classroomSaveNote: `${NODE_API_BASE}/classroom/save-note`,
    classroomUploadFile: `${NODE_API_BASE}/classroom/upload-file`,
    classroomDeleteFile: `${NODE_API_BASE}/classroom/delete-file`,
    classroomDownloadFile: `${NODE_API_BASE}/classroom/download-file`,
    classroomShareMaterial: `${NODE_API_BASE}/classroom/share-material`,
    classroomStopMaterialSharing: `${NODE_API_BASE}/classroom/stop-material-sharing`,
    classroomBoard: `${NODE_API_BASE}/classroom/board`,
    classroomBoardStrokes: `${NODE_API_BASE}/classroom/board/strokes`,
    classroomBoardTexts: `${NODE_API_BASE}/classroom/board/texts`,
    classroomBoardClear: `${NODE_API_BASE}/classroom/board/clear`,
    studentTeachers: `${NODE_API_BASE}/student/teachers`,
    findTeachers: `${NODE_API_BASE}/teachers`,
    studentTeacher: `${NODE_API_BASE}/teachers/details`,
    sendTeacherRequest: `${NODE_API_BASE}/teachers/requests`,
    teacherStudents: `${NODE_API_BASE}/teacher/students`,
    teacherStudentDetails: `${NODE_API_BASE}/teacher/student-details`,
    updateTeacherStudentStatus: `${NODE_API_BASE}/teacher/students/status`,
    respondStudentRequest: `${NODE_API_BASE}/teacher/student-requests/respond`,
    teacherLessonOptions: `${NODE_API_BASE}/lessons/options`,
    createTeacherLesson: `${NODE_API_BASE}/lessons`,
    messageDialogs: `${NODE_API_BASE}/messages/dialogs`,
    messageThread: `${NODE_API_BASE}/messages/thread`,
    sendMessage: `${NODE_API_BASE}/messages/send`,
    markMessagesRead: `${NODE_API_BASE}/messages/read`,
    messageDownload: `${NODE_API_BASE}/messages/download`,
    reportMessage: `${NODE_API_BASE}/messages/report`,
    adminMessages: `${NODE_API_BASE}/admin/messages`,
    adminProfileMedia: `${NODE_API_BASE}/admin/profile-media`,
    notifications: `${NODE_API_BASE}/notifications`,
    parentNotificationSettings: `${NODE_API_BASE}/notifications/parent-settings`,
    markNotificationsRead: `${NODE_API_BASE}/notifications/read`,
    deleteNotification: `${NODE_API_BASE}/notifications/delete`,
    clearNotifications: `${NODE_API_BASE}/notifications/clear`,
    reviews: `${NODE_API_BASE}/reviews`,
    publicTariffs: `${NODE_API_BASE}/tariffs/public`,
    saveReview: `${NODE_API_BASE}/reviews`,
    replyReview: `${NODE_API_BASE}/reviews/reply`,
};

export function getAuthToken()
{
    return sessionStorage.getItem('gostudy_token') || '';
}

export function getAuthHeaders()
{
    const token = getAuthToken();

    return token
        ? {
            'Content-Type': 'application/json',
            'X-Auth-Token': token,
        }
        : {
            'Content-Type': 'application/json',
        };
}
